version: "3.7"

services:

  worker0:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      CAPE_BROKER: https://demo.capeprivacy.com/broker
      CAPE_COORDINATOR: https://demo.capeprivacy.com

  worker1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      CAPE_BROKER: https://demo.capeprivacy.com/broker
      CAPE_COORDINATOR: https://demo.capeprivacy.com

  worker2:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      CAPE_BROKER: https://demo.capeprivacy.com/broker
      CAPE_COORDINATOR: https://demo.capeprivacy.com

  worker3:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      CAPE_BROKER: https://demo.capeprivacy.com/broker
      CAPE_COORDINATOR: https://demo.capeprivacy.com
