[package]
name = "reindeer"
version = "0.1.0"
license = "MIT"
edition = "2018"
authors = []
default-run = "rudolph"

[dependencies]
async-trait = "~0.1"
anyhow = "~1.0"
async_cell = "~0.2"
bincode = "~1.3"
dashmap = "~5.1"
maplit = "~1.0"
moose = { path = "../moose", default-features = false, features = ["async_execute"] }
moose-modules = { path = "../modules" }
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0"
structopt = "~0.3"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.6"
tracing = { version="0.1", features = ["log"] }
tracing-subscriber = "0.3"

[[bin]]
name = "rudolph"
path = "src/rudolph.rs"

[[bin]]
name = "dasher"
path = "src/dasher.rs"

[[bin]]
name = "vixen"
path = "src/vixen.rs"
