name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ubuntu-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Rust.
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: Swatinem/rust-cache@v1

      - name: Install OpenBLAS.
        run: |
          sudo apt install libopenblas-dev

      - name: Install build dependencies
        run: |
          sudo apt install -y make clang protobuf-compiler

      - name: Create virtual environment.
        run: |
          python -m venv venv

      - name: Install dependencies.
        run: |
          . venv/bin/activate
          make pydep

      - name: Install runtime package.
        run: |
          . venv/bin/activate
          make pylib

      - name: Lint check the runtime package.
        run: |
          . venv/bin/activate
          make lint

      - name: Test the runtime.
        run: |
          . venv/bin/activate
          make test-ci
